# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import main
import cv2
import Ui2

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(699, 466)
        self.cityNameLine = QtWidgets.QLabel(Dialog)
        self.cityNameLine.setGeometry(QtCore.QRect(50, 40, 91, 21))
        self.cityNameLine.setObjectName("cityNameLine")
        font=QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.cityLine = QtWidgets.QLineEdit(Dialog)
        self.cityLine.setGeometry(QtCore.QRect(140, 40, 101, 20))
        self.cityLine.setObjectName("cityLine")
        self.cityLine.setText('北京')
        self.search = QtWidgets.QPushButton(Dialog)
        self.search.setGeometry(QtCore.QRect(260, 40, 75, 23))
        self.search.setObjectName("search")

        self.show_temprae = QtWidgets.QPushButton(Dialog)
        self.show_temprae.setGeometry(QtCore.QRect(570, 40, 91, 23))
        self.show_temprae.setObjectName("show_temprae")


        self.showCityList = QtWidgets.QPushButton(Dialog)
        self.showCityList.setGeometry(QtCore.QRect(440, 40, 101, 23))
        self.showCityList.setObjectName("showForecast")
        self.forecastData=QtWidgets.QTextEdit(Dialog)
        self.forecastData.setGeometry(QtCore.QRect(440,110,231,311))
        self.forecastData.setObjectName('forecastData')
        self.city_name = QtWidgets.QLabel(Dialog)
        self.city_name.setGeometry(QtCore.QRect(130, 100, 51, 51))
        self.city_name.setObjectName("city_name")
        self.date = QtWidgets.QLabel(Dialog)
        self.date.setGeometry(QtCore.QRect(130, 140, 241, 20))
        self.date.setObjectName("date")
        self.weather_img = QtWidgets.QLabel(Dialog)
        self.weather_img.setGeometry(QtCore.QRect(60, 191, 61, 51))
        self.weather_img.setObjectName("weather_img")
        self.now_tempera = QtWidgets.QLabel(Dialog)
        self.now_tempera.setGeometry(QtCore.QRect(150, 200, 81, 31))
        self.now_tempera.setObjectName("now_tempera")
        self.today_tempare = QtWidgets.QLabel(Dialog)
        self.today_tempare.setGeometry(QtCore.QRect(140, 230, 54, 12))
        self.today_tempare.setObjectName("today_tempare")
        self.sunUpDate = QtWidgets.QLabel(Dialog)
        self.sunUpDate.setGeometry(QtCore.QRect(240, 330, 91, 20))
        self.sunUpDate.setObjectName("sunUpDate")
        self.sunDownDate = QtWidgets.QLabel(Dialog)
        self.sunDownDate.setGeometry(QtCore.QRect(240, 350, 71, 20))
        self.sunDownDate.setObjectName("sunDownDate")
        self.city_img = QtWidgets.QLabel(Dialog)
        self.city_img.setGeometry(QtCore.QRect(43, 90, 61, 61))
        self.city_img.setObjectName("city_img")
        self.shidu = QtWidgets.QLabel(Dialog)
        self.shidu.setGeometry(QtCore.QRect(40, 280, 71, 16))
        self.shidu.setObjectName("shidu")
        self.fx = QtWidgets.QLabel(Dialog)
        self.fx.setGeometry(QtCore.QRect(110, 280, 101, 16))
        self.fx.setObjectName("fx")
        self.uv = QtWidgets.QLabel(Dialog)
        self.uv.setGeometry(QtCore.QRect(210, 280, 81, 16))
        self.uv.setObjectName("uv")
        self.kongqi = QtWidgets.QLabel(Dialog)
        self.kongqi.setGeometry(QtCore.QRect(40, 330, 121, 31))
        self.kongqi.setObjectName("kongqi")
        self.PM = QtWidgets.QLabel(Dialog)
        self.PM.setGeometry(QtCore.QRect(170, 340, 54, 12))
        self.PM.setObjectName("PM")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def searchClick(self):
        cityName = self.cityLine.text()
        print(cityName)
        week, now_tempera, today_tempera, shidu_list, kognqi ,weather_img_path= main.getWeatherData(cityName)

        # self.city_img.setPixmap(QtGui.QPixmap('C:/Users/jiongjiong/Desktop/安岳')
        # .scaled(self.city_img.height(), self.city_img.width()))
        print(QtGui.QPixmap('C:/Users/jiongjiong/PycharmProjects/WeatherShow/cityImg/'+cityName)
              .scaled(self.city_img.height(),self.city_img.width()))
        self.city_img.setPixmap(QtGui.QPixmap('C:/Users/jiongjiong/PycharmProjects/WeatherShow/cityImg/'+cityName)
                                .scaled(self.city_img.height(),self.city_img.width()))



        self.weather_img.setPixmap(QtGui.QPixmap(weather_img_path))
        self.city_name.setText(cityName)
        self.date.setText(week)
        self.now_tempera.setText(today_tempera[0]+' '+now_tempera)
        self.today_tempare.setText(today_tempera[1])
        self.shidu.setText(shidu_list[0])
        self.fx.setText(shidu_list[1])
        self.uv.setText(shidu_list[2])
        self.kongqi.setText(kognqi[0])
        self.PM.setText(kognqi[1])
        self.sunUpDate.setText(kognqi[2])
        self.sunDownDate.setText(kognqi[3])
        return
    def showForecast(self):
        cityName = self.cityLine.text()
        forecast=main.get_weather_data(cityName)
        self.forecastData.setText(
            '           ' + cityName + '未来五天天气\n'
            + forecast[0].get('date') + '\n'
                                        '      天气：' + forecast[0].get('type') + '\n'
                                                                                '      温度：' + forecast[0].get(
                'low') + '——' + forecast[0].get('high') + '\n'
                                                         '      风向：' + forecast[0].get('fengxiang') + '\n'
                                                                                                      '      风级：' +
            forecast[0].get('fengli') + '\n\n'

            + forecast[1].get('date') + '\n'
                                        '      天气：' + forecast[1].get('type') + '\n'
                                                                                '      温度：' + forecast[1].get(
                'low') + '——' + forecast[0].get('high') + '\n'
                                                         '      风向：' + forecast[1].get('fengxiang') + '\n'
                                                                                                      '      风级：' +
            forecast[1].get('fengli') + '\n\n'

            + forecast[2].get('date') + '\n'
                                        '      天气：' + forecast[2].get('type') + '\n'
                                                                                '      温度：' + forecast[2].get(
                'low') + '——' + forecast[0].get('high') + '\n'
                                                         '      风向：' + forecast[2].get('fengxiang') + '\n'
                                                                                                      '      风级：' +
            forecast[2].get('fengli') + '\n\n'

            + forecast[3].get('date') + '\n'
                                        '      天气：' + forecast[3].get('type') + '\n'
                                                                                '      温度：' + forecast[3].get(
                'low') + '——' + forecast[0].get('high') + '\n'
                                                         '      风向：' + forecast[3].get('fengxiang') + '\n'
                                                                                                      '      风级：' +
            forecast[3].get('fengli') + '\n\n'

            + forecast[4].get('date') + '\n'
                                        '      天气：' + forecast[4].get('type') + '\n'
                                                                                '      温度：' + forecast[4].get(
                'low') + '——' + forecast[0].get('high') + '\n'
                                                         '      风向：' + forecast[4].get('fengxiang') + '\n'
                                                                                                      '      风级：' +
            forecast[4].get('fengli') + '\n\n'
        )
    def show_tempraeClick(self):
        cityName = self.cityLine.text()
        main.get_weather_data(cityName)
        self.form2 = QtWidgets.QWidget()
        self.ui2 = Ui2.Ui_Form()
        self.ui2.setupUi(self.form2)
        self.form2.show()
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "天气查询"))
        self.cityNameLine.setText(_translate("Dialog", "请输入城市名"))
        self.search.setText(_translate("Dialog", "查找"))
        self.showCityList.setText(_translate("Dialog", "查询未来五天"))
        self.show_temprae.setText(_translate("Dialog", " 显示温度曲线"))
        self.city_name.setText(_translate("Dialog", "  北京"))
        self.date.setText(_translate("Dialog", "2020年12月16日　星期三　庚子年冬月初二 "))
        self.weather_img.setText(_translate("Dialog", "  图片"))
        self.now_tempera.setText(_translate("Dialog", "1℃"))
        self.today_tempare.setText(_translate("Dialog", "-8 ~ 2℃"))
        self.sunUpDate.setText(_translate("Dialog", "日出: 07:29"))
        self.sunDownDate.setText(_translate("Dialog", "日落: 16:50"))
        self.city_img.setText(_translate("Dialog", "   图片"))
        self.shidu.setText(_translate("Dialog", " 湿度：23% "))
        self.fx.setText(_translate("Dialog", " 风向：南风 2级"))
        self.uv.setText(_translate("Dialog", " 紫外线：无"))
        self.kongqi.setText(_translate("Dialog", " 空气质量：优"))
        self.PM.setText(_translate("Dialog", " PM: 26"))
        self.search.clicked.connect(self.searchClick)
        self.show_temprae.clicked.connect(self.show_tempraeClick)
        self.showCityList.clicked.connect(self.showForecast)
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    w = Ui_Dialog()
    w.setupUi(form)
    form.show()
    sys.exit(app.exec_())